In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
## sentences 
sent =['this is a glass of milk',
       'this is a glass of water',
       'this is a glass of juice',
       'this is a glass of tea',
       'this is a glass of coffee']

In [6]:
## define vocab size 
voc_size =10000

In [7]:
## one hot encoding
one_hot_rep=[one_hot(words,voc_size)for words in sent]

In [8]:
one_hot_rep

[[1219, 6949, 6781, 2104, 1656, 5925],
 [1219, 6949, 6781, 2104, 1656, 9342],
 [1219, 6949, 6781, 2104, 1656, 601],
 [1219, 6949, 6781, 2104, 1656, 6362],
 [1219, 6949, 6781, 2104, 1656, 8511]]

In [9]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [10]:
sen_length =8
embedded_docs =pad_sequences(one_hot_rep,padding='pre',maxlen=sen_length)
print(embedded_docs)

[[   0    0 1219 6949 6781 2104 1656 5925]
 [   0    0 1219 6949 6781 2104 1656 9342]
 [   0    0 1219 6949 6781 2104 1656  601]
 [   0    0 1219 6949 6781 2104 1656 6362]
 [   0    0 1219 6949 6781 2104 1656 8511]]


In [14]:
## feature represnetation
dim=10
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sen_length))
model.compile('adam','mse')

model.summary()

d:\DataScienceBootCamp\python\venv1\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[ 0.02349776,  0.01017042,  0.02953292, -0.03439262,
          0.01107948,  0.04391376,  0.04029128,  0.04076095,
          0.00285206, -0.04801385],
        [ 0.02349776,  0.01017042,  0.02953292, -0.03439262,
          0.01107948,  0.04391376,  0.04029128,  0.04076095,
          0.00285206, -0.04801385],
        [ 0.0128285 ,  0.04736397, -0.04691057,  0.00528927,
          0.03485018, -0.0492509 ,  0.04669461, -0.04988614,
          0.04984487, -0.02350451],
        [-0.0188905 , -0.02420632,  0.00838312, -0.01966034,
         -0.00640571,  0.00478773, -0.03829986, -0.0150523 ,
          0.02011526, -0.01219849],
        [ 0.02060603, -0.03988204,  0.03948914,  0.00591464,
          0.04896061, -0.04931137, -0.02572359, -0.0473243 ,
         -0.0040251 ,  0.00795761],
        [-0.03963172, -0.04723397, -0.01576873,  0.02499184,
         -0.04401547, -0.01700443, -0.00524199,  0.01192417,
          0.02136138,  0.04535795],
        [-0.02231896, -0.00357524, -0.02134043,  0.0

In [16]:
sent[0]

'this is a glass of milk'

In [17]:
embedded_docs[0]

array([   0,    0, 1219, 6949, 6781, 2104, 1656, 5925], dtype=int32)